version: '3'
services:
    edm-mysql:
        image: elastest/edm-mysql:latest
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: "elastest"
            MYSQL_USER: elastest
            MYSQL_PASSWORD: elastest
        ports:
            - "3306:3306"
        volumes:
            - edm-mysql:/var/lib/mysql
            - ./resources/mysql/config:/etc/mysql/conf.d
        networks:
            - elastest

    edm-elasticsearch:
        image: elastest/etm-elasticsearch:latest
        ports:
            - "9200:9200"
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        environment:
            - xpack.security.enabled=false
            - http.host=0.0.0.0
            - transport.host=127.0.0.1
            - ES_JAVA_OPTS=-Xmx3g -Xms3g
        networks:
            - elastest
volumes:
    elasticsearch-data:
      driver: local
    edm-mysql:
      driver: local
networks:
    elastest:
      driver: bridge
