apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    elastest-component: edm-mysql
    elastest-component-type: volumen
  name: edm-mysql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standar
status: {}
