apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    elastest-component: esdata1
    elastest-component-type: volume
  name: esdata1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
status: {}
