# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  # config.vm.box_check_update = false

  # Additional ports are needed for services like the ElasTest Jenkins plugin
  # ElasTest needs to be able to bind ports in the range 37001-65535
  # config.vm.network "forwarded_port", guest: 37000, host: 37000

  config.vm.network "private_network", ip: "192.168.37.37"

  config.disksize.size = "30GB"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8096"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y curl
    curl -fsSL get.docker.com -o get-docker.sh
    sh get-docker.sh
    usermod -aG docker ubuntu

    # Create a swap file
    fallocate -l 4G /swapfile
    chmod 0600 /swapfile
    mkswap /swapfile
    swapon /swapfile
    free -m

    # Increase map_max_count for ElasticSearch
    sysctl -w vm.max_map_count=262144
    echo vm.max_map_count=262144 >> /etc/sysctl.conf

    # Start ElasTest platform with the IP specified above
    docker run --rm -d -v /var/run/docker.sock:/var/run/docker.sock elastest/platform start -sa=192.168.37.37 -m experimental

  SHELL
end
