apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etm-deploy
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elastest
        elastest-service: etm
        elastest-component-type: core
        elastest-component: etm
    spec:
      containers:
      - name: etm
        image: elastest/etm:dev-local
        command:
        - /run.sh
        env:
        - name: ET_DATA_IN_HOST
          value: ~/.elastestK8s
        - name: ET_EDM_MYSQL_HOST
          value: edm-mysql
        - name: ET_EDM_MYSQL_PORT
          value: "3306"
        - name: ET_ENABLE_CLOUD_MODE
          value: "true"
        - name: ET_EPM_API
          value: http://epm:8180/v1
        - name: ET_EPM_BINDED_PORT
          value: "8180"
        - name: ET_EPM_K8S_MASTER
          value: 192.168.1.41
        - name: ET_EPM_K8S_TOKEN
          value: none
        - name: ET_ESM_API
          value: http://esm:37005/
        - name: ET_ESM_SS_DESC_FILES_PATH
          value: /platform-services
        - name: ET_ETM_API
          value: http://etm:8091/
        - name: ET_ETM_INCONTAINER
          value: "true"
        - name: ET_ETM_INTERNAL_HOST
          value: etm
        - name: ET_ETM_JENKINS_HOST
          value: none
        - name: ET_ETM_LOG_LEVEL
          value: DEBUG
        - name: LOGSTASH_HOST
          value: etm-logstash 
        - name: ET_ETM_LSBEATS_HOST
          value: etm-logstash
        - name: ET_ETM_LSHTTP_API
          value: http://etm-logstash:5003/
        - name: ET_ETM_LSTCP_HOST
          value: etm-logstash
        - name: ET_ETM_RABBIT_HOST
          value: etm-rabbitmq
        - name: ET_ETM_TESTLINK_API_KEY
          value: none
        - name: ET_ETM_TESTLINK_HOST
          value: none
        - name: ET_IN_PROD
          value: "true"
        - name: ET_PASS
          value: none
        - name: ET_PROXY_HOST
          value: etm-proxy
        - name: ET_PROXY_PORT
          value: "37000"
        - name: ET_PUBLIC_HOST
          value: 192.168.1.41
        - name: ET_PUBLIC_HOST_TYPE
          value: server_address
        - name: ET_USER
          value: none
        - name: EXEC_MODE
          value: singlenode
        - name: HOST_TIMEZONE
          value: UTC
        resources: {}
        volumeMounts:
        - mountPath: /platform-services
          name: platform-services
        - mountPath: /data
          name: elastest-data
      restartPolicy: Always
      volumes:
      - name: platform-services
        persistentVolumeClaim:
          claimName: platform-services
      - name: elastest-data
        persistentVolumeClaim:
          claimName: elastest-data-claim
status: {}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: default-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
