apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    elastest-component: etm-rabbitmq
  name: etm-rabbitmq
spec:
  ports:
  - name: "15672"
    port: 15672
    targetPort: 15672
  - name: "5672"
    port: 5672
    targetPort: 5672
  - name: "15671"
    port: 15671
    targetPort: 15671
  - name: "25672"
    port: 25672
    targetPort: 25672
  - name: "61613"
    port: 61613
    targetPort: 61613
  selector:
    elastest-component: etm-rabbitmq
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    elastest-component: etm-logstash
  name: etm-logstash
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  - name: "5037"
    port: 5037
    targetPort: 5037
  - name: "5044"
    port: 5044
    targetPort: 5044
  - name: "5001"
    port: 5001
    targetPort: 5001
  - name: "5002"
    port: 5002
    targetPort: 5002
  - name: "5003"
    port: 5003
    targetPort: 5003
  selector:
    elastest-component: etm-logstash
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    elastest-component-type: core
    elastest-component: etm-rabbitmq
  name: etm-rabbitmq
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        elastest-component-type: core
        elastest-component: etm-rabbitmq
    spec:
      containers:
      - image: elastest/etm-rabbitmq:latest
        name: etm-rabbitmq
        ports:
        - containerPort: 15672
        - containerPort: 5672
        - containerPort: 15671
        - containerPort: 25672
        - containerPort: 61613
        resources: {}
      hostname: my-rabbit
      restartPolicy: Always
status: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    elastest-component-type: core
    elastest-component: etm-logstash
  name: etm-logstash
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        elastest-component-type: core
        elastest-component: etm-logstash
    spec:
      containers:
      - env:
        - name: ELASTICHOST
          value: edm-elasticsearch
        - name: RABBITHOST
          value: etm-rabbitmq
        - name: RABBITPASS
          value: elastest-etm
        - name: RABBITUSER
          value: elastest-etm
        image: elastest/etm-logstash:latest
        name: etm-logstash
        ports:
        - containerPort: 5000
        - containerPort: 5037
        - containerPort: 5044
        - containerPort: 5001
        - containerPort: 5002
        - containerPort: 5003
        resources: {}
      restartPolicy: Always
status: {}