apiVersion: v1
kind: Service
metadata:
  name: emp-kafka
  labels:
    elastest-component: emp-kafka
spec:
  ports:
  - name: "2181"
    port: 2181
    targetPort: 2181
    nodePort: 2181
  - name: "9092"
    port: 9092
    targetPort: 9092
    nodePort: 9092
  selector:
    elastest-component: emp-kafka
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: emp-influxdb
  labels:
    elastest-component: emp-influxdb
spec:
  ports:
  - name: "8083"
    port: 8083
    targetPort: 8083
    nodePort: 8083
  - name: "8086"
    port: 8086
    targetPort: 8086
    nodePort: 8086
  - name: "2003"
    port: 2003
    targetPort: 2003
    nodePort: 2003
  selector:
    elastest-component: emp-influxdb
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: emp-grafana
  labels:
    elastest-component: emp-grafana
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
    nodePort: 3000
  selector:
    elastest-component: emp-grafana
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: emp
  labels:
    app: emp
    elastest-component: emp
    io.elastest.service: etm-proxy
spec:
  ports:
  - name: "9100"
    port: 9100
    targetPort: 9100
  selector:
    elastest-component: emp
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    elastest-component: emp-kafka
    elastest-component-type: core
  name: emp-kafka
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        elastest-component: emp-kafka
        elastest-component-type: core
    spec:
      containers:
      - env:
        - name: ADVERTISED_HOST
          value: emp-kafka
        - name: ADVERTISED_LISTENERS
          value: emp-kafka
        - name: ADVERTISED_PORT
          value: "9092"
        - name: LISTENERS
          value: PLAINTEXT://localhost:9092
        image: spotify/kafka
        name: emp-kafka
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    elastest-component: emp-influxdb
    elastest-component-type: core
  name: emp-influxdb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        elastest-component: emp-influxdb
        elastest-component-type: core
    spec:
      containers:
      - env:
        - name: INFLUXDB_ADMIN_ENABLED
          value: "true"
        - name: INFLUXDB_GRAPHITE_ENABLED
          value: "true"
        - name: INFLUXDB_HTTP_AUTH_ENABLED
          value: "true"
        image: influxdb:1.2.4-alpine
        name: emp-influxdb
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    elastest-component: emp-grafana
    elastest-component-type: core
  name: emp-grafana
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        elastest-component: emp-grafana
        elastest-component-type: core
    spec:
      containers:
      - env:
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_NAME
          value: Main Org.
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Viewer
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: 1ccl@b2017
        - name: GF_SERVER_DOMAIN
          value: 99.81.234.102:37000
        - name: GF_SERVER_ROOT_URL
          value: '%(protocol)s://%(domain)s:/grafana'
        image: grafana/grafana:4.6.1
        name: emp-grafana
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    elastest-component: emp-system-agent
    elastest-component-type: core
  name: emp-system-agent
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        elastest-component: emp-system-agent
        elastest-component-type: core
    spec:
      containers:
      - env:
        - name: KAFKA_ENDPOINT
          value: emp-kafka:9092
        - name: KAFKA_KEY_SERIALIZER
          value: StringSerializer
        - name: KAFKA_VALUE_SERIALIZER
          value: StringSerializer
        - name: PERIODICITY
          value: "30"
        - name: SENTINEL_SERIES
          value: sys-stats
        - name: SENTINEL_TOPIC
          value: user-1-elastest_core
        image: elastest/emp-system-agent:latest
        name: emp-system-agent
        resources: {}
      restartPolicy: Always
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    elastest-component: emp-docker-agent
    elastest-component-type: core
  name: emp-docker-agent
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        elastest-component: emp-docker-agent
        elastest-component-type: core
    spec:
      containers:
      - env:
        - name: KAFKA_ENDPOINT
          value: emp-kafka:9092
        - name: KAFKA_KEY_SERIALIZER
          value: StringSerializer
        - name: KAFKA_VALUE_SERIALIZER
          value: StringSerializer
        - name: SENTINEL_TOPIC
          value: user-1-elastest_core
        - name: SENTINEL_SERIES
          value: docker-stats
        - name: DOCKER_SOCKET
          value: unix://var/run/docker.sock
        - name: PERIODICITY
          value: "60"
        image: elastest/emp-docker-agent:latest
        name: emp-docker-agent
        resources: {}
        volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    elastest-component: emp
    elastest-component-type: core
  name: emp
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        elastest-component: emp
        elastest-component-type: core
    spec:
      containers:
      - env:
        - name: ADMIN_TOKEN
          value: somevalue
        - name: DASHBOARD_ENDPOINT
          value: 99.81.234.102:37000/grafana
        - name: DASHBOARD_TITLE
          value: elastest
        - name: ET_EDM_ALLUXIO_API
          value: http://edm-alluxio-master:19999/
        - name: ET_EDM_API
          value: http://edm:37003/
        - name: ET_EDM_ELASTICSEARCH_API
          value: http://edm-elasticsearch:9200/
        - name: ET_EDM_MYSQL_HOST
          value: edm-mysql
        - name: ET_EDM_MYSQL_PORT
          value: "3306"
        - name: ET_EIM_API
          value: http://eim:37004/
        - name: ET_EMP_API
          value: http://eim:37001/
        - name: ET_EMP_INFLUXDB_API
          value: http://emp-influxdb:8086/
        - name: ET_EMP_INFLUXDB_GRAPHITE_PORT
          value: "2003"
        - name: ET_EMP_INFLUXDB_HOST
          value: emp-influxdb
        - name: ET_EPM_API
          value: http://epm:37002/
        - name: ET_ESM_API
          value: http://esm:37005/
        - name: ET_ETM_API
          value: http://etm:37006/
        - name: ET_ETM_LSBEATS_HOST
          value: etm-beats
        - name: ET_ETM_LSBEATS_PORT
          value: "5044"
        - name: ET_ETM_LSHTTP_API
          value: http://etm-logstash:5002/
        - name: ET_ETM_RABBIT_HOST
          value: etm-rabbitmq
        - name: ET_ETM_RABBIT_PORT
          value: "5672"
        - name: GRAFANA_ADMIN
          value: admin
        - name: GRAFANA_PASSWORD
          value: 1ccl@b2017
        - name: GRAFANA_URL
          value: http://emp-grafana:3000
        - name: INFLUX_PASSWORD
          value: pass1234
        - name: INFLUX_URL
          value: http://emp-influxdb:8086
        - name: INFLUX_URL_GRAFANA
          value: http://emp-influxdb:8086
        - name: INFLUX_USER
          value: root
        - name: KAFKA_ENDPOINT
          value: emp-kafka:9092
        - name: PROXY_WORKAROUND_ENABLE
          value: "false"
        - name: PROXY_WORKAROUND_LOCATION
          value: /emp-admin
        - name: PROXY_WORKAROUND_TYPE
          value: nginx
        - name: SENTINEL_DB_ENDPOINT
          value: /data/sentinel.db
        - name: STREAM_ACCESSURL
          value: nightly.elastest.io:37000/influxui
        - name: STREAM_ADMINPASS
          value: pass1234
        - name: STREAM_ADMINUSER
          value: root
        - name: STREAM_DBENDPOINT
          value: emp-influxdb:8086
        - name: STREAM_DBTYPE
          value: influxdb
        - name: TOPIC_CHECK_INTERVAL
          value: "30000"
        - name: ZOOKEEPER_ENDPOINT
          value: emp-kafka:2181
        image: elastest/emp:latest
        name: emp
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: emp
      restartPolicy: Always
      volumes:
      - name: emp
        persistentVolumeClaim:
          claimName: emp
status: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    elastest-component: emp-k8s-agent
    elastest-component-type: core
  name: emp-k8s-agent
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        elastest-component: emp-k8s-agent
        elastest-component-type: core
    spec:
      containers:
      - env:
        - name: host
          value: emp-kafka
        - name: port
          value: "9092"
        - name: topic
          value: user-1-elastest_core
        - name: series
          value: kubernetes
        - name: clientid
          value: sentinel-k8s-client
        - name: periodicity
          value: "30"
        - name: mode
          value: incluster
        image: elastest/emp-k8s-agent:latest
        name: emp-k8s-agent
        resources: {}
      restartPolicy: Always
status: {}
