apiVersion: v1
kind: Service
metadata:
  name: edm-mysql
  labels:
    app: elastest
    elastest-component: edm-mysql
    io.elastest.service: edm-mysql
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
    nodePort: 3306
  selector:
    elastest-service: edm-mysql
  type: NodePort
status:
  loadBalancer: {}
