apiVersion: v1
kind: Service
metadata:
  labels:
    app: elastest
    elastest-component: epm
    io.elastest.service: epm
  name: epm
spec:
  ports:
  - name: "epm-port"
    port: 8180
    targetPort: 8180
    nodePort: 8180
  selector:
    elastest-service: epm
  type: NodePort
status:
  loadBalancer: {}
