apiVersion: v1
kind: Service
metadata:
  name: etm-proxy
  labels:
    app: elastest
    elastest-component: etm-proxy
    io.elastest.service: etm-proxy
spec:
  ports:
  - name: "37000"
    port: 37000
    targetPort: 80
    nodePort: 37000
  - name: "37443"
    port: 37443
    targetPort: 443
    nodePort: 37443
  selector:
    elastest-service: etm-proxy
  type: NodePort
status:
  loadBalancer: {}
