version: '3'
services:
    platform-services:
        image: elastest/platform-services
        volumes:
            - esm_services:/platform-services
        networks:
            - elastest
networks:
    elastest:
      driver: bridge
volumes:
    esm_services:
      driver: local
