version: '3'
services:
    platform-services:
        image: elastest/platform-services:dev
        volumes:
            - platform-services:/platform-services
        networks:
            - elastest
networks:
    elastest:
      driver: bridge
volumes:
    platform-services:
      driver: local
